cidr_block = "10.0.0.0/16"
instance_tenancy = "default"
vpc_name = "test01-dev-vpc"
my_igw_name = "test12121-igw"
my_public_subnet_name = "testingabc-pub-subnet"
my_public_subnet_cidr_block = "10.0.1.0/24"
my_public_subnet_route_table_name = "testingxyz-pub-rt"
route_for_igw_destination_cidr_block = "0.0.0.0/0"
