cidr_block = "10.2.0.0/16"
instance_tenancy = "default"
vpc_name = "test02-dev-vpc"
my_igw_name = "test2-igw"
my_public_subnet_name = "test2-pub-subnet"
my_public_subnet_cidr_block = "10.2.1.0/24"
my_public_subnet_route_table_name = "test2-pub-rt"
route_for_igw_destination_cidr_block = "0.0.0.0/0"
